allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

catalogs:
  dev:
    "@arethetypeswrong/core": 0.18.4
    "@astrojs/ts-plugin": ^1.10.9
    "@tailwindcss/vite": ^4.3.1
    "@types/node": 26.0.1
    "@typescript-eslint/parser": ^8.62.0
    "@typescript/native-preview": 7.0.0-dev.20260624.1
    "@virtual-live-lab/tsconfig": 2.1.23
    eslint: ^10.6.0
    eslint-plugin-astro: ^2.1.1
    eslint-plugin-better-tailwindcss: ^4.6.0
    eslint-plugin-jsx-a11y: ^6.10.2
    pkg-pr-new: 0.0.75
    prettier: ^3.9.0
    prettier-plugin-astro: ^0.14.1
    publint: 0.3.21
    release-it: 20.2.0
    release-it-pnpm: 4.6.6
    tailwindcss: ^4.3.1
    typescript: 6.0.3
    typescript-eslint: ^8.62.0
    unplugin-icons: ^23.0.1
    unplugin-unused: 0.5.7
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vitest: 4.1.9
    vite-plus: latest
    wrangler: ^4.105.0
  prod:
    "@astrojs/cloudflare": ^14.0.1
    astro: ^7.0.3
    astro-seo: ^1.1.0
    cnfast: ^0.0.8
    temporal-polyfill-lite: ^0.4.1

configDependencies:
  "@pnpm/pacquet": 0.11.12

minimumReleaseAgeExclude:
  - prettier@3.9.0
  - eslint@10.6.0

saveExact: true

overrides:
  vite: "catalog:dev"
  vitest: "catalog:dev"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
